services:
  app:
    build: .
    container_name: prox3
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy
      dragonfly:
        condition: service_started

  postgres:
    image: postgres:18
    container_name: postgres18
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: dragonfly
    restart: unless-stopped
    ulimits:
      memlock: -1

    env_file:
      - .env

    command: >
      dragonfly
      --requirepass ${REDIS_PASSWORD}

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - dragonfly_data:/data

    healthcheck:
      disable: true

volumes:
  postgres_data:
  dragonfly_data:

